### ISSUE TITLE
Crashes - Won't Launch

### ISSUE THREAD

**Issue by Graywaren** [UpcraftLP/Rift-WorldInfo#2]
Mod prevents my game from opening. Not just loading a world, it prevents the whole program from launching.

Using:
1.13.2 & Rift
MultiMC launcher

No other mods installed doesn't make a difference. 

Log says:
[14:49:26] [main/INFO]: loaded World Info HUD!
[14:49:26] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: alv
	at com.github.upcraftlp.worldinfo.WorldInfo.registerVanillaEntityHandlers(WorldInfo.java:83) ~[WorldInfo.class:1.0.0]
	at com.github.upcraftlp.worldinfo.WorldInfo.onMinecraftStart(WorldInfo.java:79) ~[WorldInfo.class:1.0.0]
	at pf.handler$beforeBootstrapRegister$zbc000(SourceFile:607) ~[pf.class:?]
	at pf.c(SourceFile) ~[pf.class:?]
	at cft.<init>(SourceFile:370) ~[cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: alv
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at com.github.upcraftlp.worldinfo.WorldInfo.registerVanillaEntityHandlers(WorldInfo.java:83) ~[WorldInfo.class:1.0.0]
	at com.github.upcraftlp.worldinfo.WorldInfo.onMinecraftStart(WorldInfo.java:79) ~[WorldInfo.class:1.0.0]
	at pf.handler$beforeBootstrapRegister$zbc000(SourceFile:607) ~[pf.class:?]
	at pf.c(SourceFile) ~[pf.class:?]
	at cft.<init>(SourceFile:370) ~[cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 14 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at com.github.upcraftlp.worldinfo.WorldInfo.registerVanillaEntityHandlers(WorldInfo.java:83) ~[WorldInfo.class:1.0.0]
	at com.github.upcraftlp.worldinfo.WorldInfo.onMinecraftStart(WorldInfo.java:79) ~[WorldInfo.class:1.0.0]
	at pf.handler$beforeBootstrapRegister$zbc000(SourceFile:607) ~[pf.class:?]
	at pf.c(SourceFile) ~[pf.class:?]
	at cft.<init>(SourceFile:370) ~[cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 14 more
Process exited with code 1.

**Comment by UpcraftLP** [comment]
currently the mod is 1.13 ONLY, and I don't plan on releasing a version for 1.13.2.
1.14 is already around the corner so I'm focusing on updating to the snapshot versions.
